const APP_SCRIPT_URL='https://script.google.com/macros/s/AKfycbxkhqBPQhNVoG1Q34opocvRF8gPN_xRtQ-ydruOAsosK-G8KJq8Wp4md8dlJTX_S79EAg/exec';
const DEMO_USERS={
 rplx:{password:'rpl123',name:'RPL Kelas X',className:'X RPL',major:'RPL',role:'player'},
 rpli:{password:'rpl123',name:'RPL Kelas XI',className:'XI RPL',major:'RPL',role:'player'},
 rplii:{password:'rpl123',name:'RPL Kelas XI B',className:'XI RPL 2',major:'RPL',role:'player'},
 rpliii:{password:'rpl123',name:'RPL Kelas XII',className:'XII RPL',major:'RPL',role:'player'},
 superadmin:{password:'admin123',name:'Superadmin',className:'ADMIN',major:'RPL',role:'admin'}
};
const questions=[
["Dasar RPL", "MCQ", "Apa tujuan utama Rekayasa Perangkat Lunak?", ["Mengembangkan software secara sistematis dan berkualitas", "Mengganti semua hardware", "Mempercepat internet", "Membuat logo"], "Mengembangkan software secara sistematis dan berkualitas"],
["Algoritma", "MCQ", "Algoritma adalah...", ["Langkah logis dan terurut untuk menyelesaikan masalah", "Bahasa pemrograman", "Database", "Kabel jaringan"], "Langkah logis dan terurut untuk menyelesaikan masalah"],
["Flowchart", "MCQ", "Simbol belah ketupat pada flowchart menunjukkan...", ["Input/output", "Proses", "Percabangan/keputusan", "Mulai/selesai"], "Percabangan/keputusan"],
["Variabel", "MCQ", "Variabel digunakan untuk...", ["Menyimpan nilai yang digunakan program", "Menghapus sistem operasi", "Menggambar UI", "Menghubungkan router"], "Menyimpan nilai yang digunakan program"],
["HTML", "MCQ", "HTML digunakan untuk...", ["Menyusun struktur halaman web", "Mengatur SQL", "Mengompilasi Java", "Mengatur DNS"], "Menyusun struktur halaman web"],
["CSS", "MCQ", "CSS digunakan untuk...", ["Mengatur tampilan halaman web", "Menyimpan password", "Menjalankan query SQL", "Mengatur server"], "Mengatur tampilan halaman web"],
["JavaScript", "MCQ", "JavaScript pada web digunakan untuk...", ["Interaksi dan logika halaman", "Mengganti CPU", "Menyimpan RAM", "Membuat kabel"], "Interaksi dan logika halaman"],
["Git", "MCQ", "Git berfungsi sebagai...", ["Version control system", "Database relasional", "Browser", "Compiler"], "Version control system"],
["GitHub", "MCQ", "GitHub dapat digunakan untuk...", ["Menyimpan dan berkolaborasi pada repository", "Mengganti monitor", "Membuat kabel", "Menambah RAM"], "Menyimpan dan berkolaborasi pada repository"],
["Debugging", "MCQ", "Debugging adalah...", ["Mencari dan memperbaiki bug", "Membuat logo", "Menghapus seluruh kode", "Membuat email"], "Mencari dan memperbaiki bug"],
["Database", "TRUEFALSE", "Pernyataan: database relasional menyimpan data dalam tabel yang dapat saling berelasi.", ["BENAR", "SALAH"], "BENAR"],
["SQL SELECT", "TRUEFALSE", "Pernyataan: SELECT digunakan untuk mengambil data dari database.", ["BENAR", "SALAH"], "BENAR"],
["SQL INSERT", "TRUEFALSE", "Pernyataan: INSERT digunakan untuk menghapus baris data.", ["BENAR", "SALAH"], "SALAH"],
["SQL UPDATE", "TRUEFALSE", "Pernyataan: UPDATE dapat mengubah nilai data yang sudah ada.", ["BENAR", "SALAH"], "BENAR"],
["SQL DELETE", "TRUEFALSE", "Pernyataan: DELETE dapat menghapus baris data.", ["BENAR", "SALAH"], "BENAR"],
["Primary Key", "SCENARIO", "Sebuah tabel siswa membutuhkan identitas unik agar dua siswa tidak memiliki ID yang sama. Apa yang dipilih?", ["Primary Key", "Foreign Key", "CSS class", "API endpoint"], "Primary Key"],
["Foreign Key", "SCENARIO", "Tabel nilai harus terhubung ke tabel siswa. Kolom penghubung pada tabel nilai paling tepat menggunakan...", ["Foreign Key", "Primary Key baru tanpa relasi", "CSS selector", "Git branch"], "Foreign Key"],
["ERD", "SCENARIO", "Sebelum membuat database aplikasi perpustakaan, guru meminta model entitas dan relasi. Dokumen yang tepat adalah...", ["ERD", "Wireframe", "Storyboard game", "README"], "ERD"],
["Normalisasi", "SCENARIO", "Satu tabel menyimpan data siswa berulang-ulang sehingga terjadi redundansi. Tindakan yang tepat adalah...", ["Normalisasi", "Menambah warna tabel", "Menghapus primary key", "Mengubah HTML"], "Normalisasi"],
["OOP", "SCENARIO", "Aplikasi sekolah memiliki objek Siswa dan Guru dengan atribut serta method. Pendekatan yang sesuai adalah...", ["OOP", "Flowchart saja", "CSS", "DNS"], "OOP"],
["Class", "CODE", "Kode JavaScript: `class Siswa { constructor(nama){ this.nama=nama; } }`. Apa yang dibuat oleh keyword class?", ["Cetak biru objek", "Query SQL", "API server", "File CSS"], "Cetak biru objek"],
["Encapsulation", "CODE", "Jika properti saldo harus tidak dapat diubah sembarangan dari luar class, konsep yang tepat adalah...", ["Encapsulation", "Inheritance", "Looping", "DNS"], "Encapsulation"],
["Inheritance", "CODE", "Class `RPLStudent extends Student` menunjukkan konsep...", ["Inheritance", "Encapsulation", "SQL JOIN", "Responsive design"], "Inheritance"],
["Polymorphism", "CODE", "Method `draw()` dapat memiliki implementasi berbeda pada `Circle` dan `Rectangle`. Ini contoh...", ["Polymorphism", "Primary key", "Normalization", "Git merge"], "Polymorphism"],
["UI", "CODE", "Sebuah tombol HTML harus memiliki teks yang jelas, kontras baik, dan mudah disentuh di HP. Fokus utama persoalan ini adalah...", ["UI", "SQL", "DNS", "Git"], "UI"],
["UX", "SCENARIO", "Siswa dapat menyelesaikan pendaftaran tanpa bingung dan alurnya terasa mudah. Hal ini terutama berkaitan dengan...", ["UX", "CPU", "SQL", "DNS"], "UX"],
["Wireframe", "SCENARIO", "Sebelum coding halaman dashboard, tim ingin menyusun posisi menu dan kartu informasi tanpa detail warna. Gunakan...", ["Wireframe", "SQL query", "Compiler", "API key"], "Wireframe"],
["Responsive", "SCENARIO", "Website harus nyaman dibuka pada HP 360px maupun laptop. Solusi utama adalah...", ["Responsive design", "Mengunci lebar 1200px", "Menghapus CSS", "Menggunakan gambar besar saja"], "Responsive design"],
["API", "SCENARIO", "Frontend membutuhkan data nilai dari server melalui endpoint. Antarmuka komunikasi yang digunakan adalah...", ["API", "BIOS", "RAM", "GPU"], "API"],
["JSON", "CODE", "Server mengirim `{ \"nama\":\"Budi\", \"nilai\":90 }`. Format data tersebut adalah...", ["JSON", "HTML", "CSS", "SQL"], "JSON"],
["HTTP", "SCENARIO", "Browser meminta resource dari server menggunakan protokol web standar. Protokol yang dimaksud adalah...", ["HTTP", "FTP untuk semua request web", "HDMI", "BIOS"], "HTTP"],
["REST", "SCENARIO", "API menyediakan `/students/12` dan menggunakan GET untuk mengambil data. Pola ini paling dekat dengan...", ["REST", "OOP", "ERD", "CSS Grid"], "REST"],
["Authentication", "SCENARIO", "Sistem meminta username dan password lalu memverifikasi identitas pengguna. Proses ini disebut...", ["Authentication", "Authorization", "Deployment", "Refactoring"], "Authentication"],
["Authorization", "SCENARIO", "Setelah login, hanya kepala sekolah yang boleh membuka menu laporan. Mekanisme ini disebut...", ["Authorization", "Authentication", "Compilation", "Normalization"], "Authorization"],
["Password Security", "SCENARIO", "Developer ingin menyimpan password pengguna. Praktik yang tepat adalah...", ["Hashing kuat dengan salt", "Plain text di JavaScript", "Dimasukkan ke URL", "Disimpan di localStorage tanpa proteksi"], "Hashing kuat dengan salt"],
["XSS", "SCENARIO", "Komentar pengguna dimasukkan langsung ke HTML tanpa sanitasi dan dapat menjalankan script. Jenis risiko ini adalah...", ["XSS", "SQL Injection", "DDoS", "Packet loss"], "XSS"],
["SQL Injection", "SCENARIO", "Query SQL dibuat dengan menggabungkan input username mentah. Pencegahan terbaik adalah...", ["Prepared/parameterized query", "Mematikan CSS", "Mengganti font", "Menghapus primary key"], "Prepared/parameterized query"],
["Unit Testing", "SCENARIO", "Developer menguji fungsi `hitungTotal()` secara terisolasi. Jenis testing ini adalah...", ["Unit testing", "Integration testing", "Load testing", "Acceptance testing"], "Unit testing"],
["Integration Testing", "SCENARIO", "Tim menguji apakah modul login berhasil berkomunikasi dengan database. Ini termasuk...", ["Integration testing", "Unit testing", "UI design", "Refactoring"], "Integration testing"],
["CI/CD", "SCENARIO", "Setiap push ke repository otomatis menjalankan test lalu build. Praktik ini merupakan bagian dari...", ["CI/CD", "Wireframing", "ERD", "OOP"], "CI/CD"],
["Deployment", "SCENARIO", "Aplikasi yang sudah diuji dipublikasikan ke server produksi. Proses tersebut disebut...", ["Deployment", "Debugging", "Wireframe", "Normalization"], "Deployment"],
["Cloud", "SCENARIO", "Sekolah menyewa server dan database melalui layanan cloud tanpa membeli server fisik. Ini merupakan penggunaan...", ["Cloud computing", "Flowchart", "CSS", "Git branch"], "Cloud computing"],
["3-Tier Architecture", "SCENARIO", "Tim memisahkan presentation, business logic, dan data access agar sistem lebih terstruktur. Arsitektur ini disebut...", ["3-tier architecture", "Monolithic CSS", "ERD", "PWA only"], "3-tier architecture"],
["MVC", "CODE", "Dalam MVC, komponen yang menangani tampilan pengguna adalah...", ["View", "Model", "Controller", "Database"], "View"],
["Git Branch", "CODE", "Developer ingin mengerjakan fitur login tanpa mengganggu branch utama. Perintah konsep yang tepat adalah membuat...", ["Branch", "Primary key", "API", "Wireframe"], "Branch"],
["Code Review", "SCENARIO", "Sebelum merge, teman satu tim membaca perubahan kode untuk mencari bug dan meningkatkan kualitas. Ini disebut...", ["Code review", "Deployment", "Normalization", "Wireframing"], "Code review"],
["Refactoring", "SCENARIO", "Program tetap menghasilkan output yang sama, tetapi kode dirapikan agar lebih mudah dipelihara. Ini disebut...", ["Refactoring", "Migration", "Authentication", "Backup"], "Refactoring"],
["Scalability", "SCENARIO", "Aplikasi sekolah harus mampu melayani 10.000 pengguna saat pendaftaran dibuka. Kemampuan yang perlu diperhatikan adalah...", ["Scalability", "Color theory", "Typography", "Wireframe"], "Scalability"],
["Performance", "SCENARIO", "Halaman dashboard sangat lambat. Tim mengurangi request tidak perlu dan mengoptimalkan query. Tujuan utamanya adalah...", ["Performance optimization", "Menambah bug", "Menghapus testing", "Mengurangi keamanan"], "Performance optimization"],
["Professional RPL", "SCENARIO", "Tim profesional memulai proyek dari requirement, membuat desain, coding, testing, version control, dokumentasi, lalu deployment. Praktik ini menunjukkan...", ["Siklus pengembangan software yang terstruktur", "Coding tanpa proses", "Menghindari testing", "Menyimpan password di source code"], "Siklus pengembangan software yang terstruktur"]
,
["Harapan untuk SMK 17 Muncar", "FORM", "LEVEL 51 — Tuliskan dengan jujur harapan, keinginan, kritik membangun, atau hal yang ingin kamu lihat berkembang di SMK 17 Muncar. Tidak ada jawaban benar atau salah.", [], ""],
["Alasan Memilih RPL", "FORM", "LEVEL 52 — Mengapa kamu memilih program keahlian RPL? Keterampilan apa yang paling ingin kamu kembangkan selama belajar RPL?", [], ""],
["Cita-cita & Karya RPL", "FORM", "LEVEL 53 — Jika kamu diberi kesempatan membuat satu aplikasi/game/sistem untuk sekolah atau masyarakat, apa yang ingin kamu kembangkan dan mengapa? Tuliskan juga cita-cita atau targetmu setelah lulus.", [], ""]
];

let state={username:null,name:null,className:null,major:null,character:'',level:1,xp:0,hp:100,score:0,answered:false};
const $=id=>document.getElementById(id);
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function send(data){if(APP_SCRIPT_URL.includes('PASTE_'))return Promise.resolve();return fetch(APP_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)}).catch(()=>{});}
function log(event,detail=''){return send({timestamp:new Date().toISOString(),event,username:state.username,name:state.name,className:state.className,major:state.major,character:state.character,level:state.level,xp:state.xp,score:state.score,detail})}
function save(){localStorage.setItem('smkPintarRPG_'+state.username,JSON.stringify(state))}
function load(){try{const x=localStorage.getItem('smkPintarRPG_'+state.username);if(x)state={...state,...JSON.parse(x)}}catch(e){}}

document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$('loginForm').classList.toggle('hidden',tab.dataset.tab!=='login');$('registerForm').classList.toggle('hidden',tab.dataset.tab!=='register')});
$('registerForm').onsubmit=e=>{e.preventDefault();const username=$('regUser').value.trim().toLowerCase();if(DEMO_USERS[username]||localStorage.getItem('registered_'+username)){toast('Username sudah digunakan');return}state={username,name:$('regName').value.trim(),className:$('regClass').value.trim(),major:$('regMajor').value,character:'',level:1,xp:0,hp:100,score:0,answered:false};localStorage.setItem('registered_'+username,JSON.stringify({password:$('regPass').value,name:state.name,className:state.className,major:state.major,role:'player'}));save();log('registration');enterGame();};
$('loginForm').onsubmit=e=>{e.preventDefault();const u=$('loginUser').value.trim().toLowerCase(),p=$('loginPass').value;let account=DEMO_USERS[u];if(!account){try{account=JSON.parse(localStorage.getItem('registered_'+u))}catch(e){}}if(!account||account.password!==p){$('loginHint').textContent='Username atau password salah.';return}state={...state,username:u,name:account.name,className:account.className,major:account.major};load();enterGame();log('login')};
function enterGame(){$('authScreen').classList.add('hidden');$('gameScreen').classList.remove('hidden');if((DEMO_USERS[state.username]||{}).role==='admin'){$('adminPanel').classList.remove('hidden');$('playerPanel').classList.add('hidden');$('sideLevel').textContent='ADMIN';$('sideXp').textContent='—';$('sideHp').textContent='—';$('playerName').textContent=state.name;$('playerClass').textContent='Dashboard';loadPlayers()}else render()}
$('logoutBtn').onclick=()=>location.reload();
function chooseCharacter(c){if(!c){toast('Pilih karakter terlebih dahulu');return}state.character=c;state.hp=c==='designer'?115:100;save();log('choose_character');render();toast('Karakter '+c.toUpperCase()+' dipilih')}document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>chooseCharacter(b.dataset.char));
$('continueBtn').onclick=()=>{if(!state.character){toast('Pilih karakter di panel kiri');return}openChallenge(state.level)};
function render(){$('characterPicker').classList.toggle('hidden',!!state.character);if(!state.character){$('playerPanel').querySelector('.welcome p').textContent='Pilih karakter untuk memulai petualangan.';$('continueBtn').textContent='⚔️ PILIH KARAKTER';}else $('continueBtn').textContent='▶ LANJUTKAN LEVEL '+state.level;$('playerName').textContent=state.name;$('playerClass').textContent=(state.className||'')+' • '+(state.major||'RPL');$('sideLevel').textContent=state.level;$('sideXp').textContent=state.xp;$('sideHp').textContent=state.hp;$('hud').textContent='LV '+state.level+'  •  XP '+state.xp+'  •  ❤️ '+state.hp+'  •  Score '+state.score;$('xpBar').style.width=(state.xp%100)+'%';$('xpLabel').textContent=(state.xp%100)+'/100 XP';$('progressText').textContent=state.level+'/53';let html='';for(let i=1;i<=53;i++)html+=`<button class="${i<=state.level?'unlocked ':''}${i===state.level?'current ':''}${i%10===0?'boss ':''}${i>=51?'bonus':''}" ${i>state.level?'disabled':''} onclick="openChallenge(${i})">${i}</button>`;$('levelGrid').innerHTML=html}
function openChallenge(level){if(!state.character){toast('Pilih karakter di panel kiri');return}if(level>state.level)return;const q=questions[level-1];state.answered=false;$('challengePanel').classList.remove('hidden');$('challengeLevel').textContent='LEVEL '+level+(level%10===0?' • BOSS':'');$('challengeType').textContent=q[1];$('challengeTitle').textContent=q[0];$('challengeQuestion').textContent=q[2];$('challengeFeedback').innerHTML='';$('submitChallenge').classList.add('hidden');$('nextLevel').classList.add('hidden');if(q[1]==='FORM'){$('challengeArea').innerHTML='<textarea id="freeAnswer" maxlength=1000 placeholder="Tulis jawabanmu dengan jujur (maks. 1000 karakter)..."></textarea>';$('submitChallenge').classList.remove('hidden');$('submitChallenge').onclick=()=>answerForm($('freeAnswer').value)}else{let options=[...q[3]].sort(()=>Math.random()-.5);$('challengeArea').innerHTML=options.map((x,i)=>`<button class="option" data-value="${escapeHtml(x)}" onclick="selectOption(this)">${escapeHtml(x)}</button>`).join('');}$('challengePanel').scrollIntoView({behavior:'smooth'});}
function escapeHtml(s){return s.replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function selectOption(btn){if(state.answered)return;document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');$('submitChallenge').classList.remove('hidden');$('submitChallenge').onclick=()=>answer(btn.dataset.value)}
function answerForm(value){if(state.answered)return;if(!value||value.trim().length<5){toast('Tulis jawaban terlebih dahulu agar refleksimu tersimpan.');return}state.answered=true;const q=questions[state.level-1];state.xp+=25;state.score+=150;state.hp=Math.min(120,state.hp+10);$('challengeFeedback').innerHTML='<div class="feedback good">💬 Jawabanmu sudah dicatat. Terima kasih sudah menjawab dengan jujur.</div>';log('reflection_response',q[0]+' | '+value.trim());if(state.level<53)state.level++;save();render();$('nextLevel').classList.remove('hidden');$('nextLevel').textContent=state.level<=53?'LANJUT':'SELESAI';$('nextLevel').onclick=()=>{$('challengePanel').classList.add('hidden');render();window.scrollTo({top:0,behavior:'smooth'})}}
function answer(value){if(state.answered)return;state.answered=true;const q=questions[state.level-1],correct=q[4];document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.dataset.value===correct)b.classList.add('correct')});if(value===correct){const gain=state.character==='coder'?22:20;state.xp+=gain;state.score+=100;state.hp=Math.min(120,state.hp+5);$('challengeFeedback').innerHTML=`<div class="feedback good">✅ BENAR! +${gain} XP • +100 Score<br>${correct}</div>`;log('answer_correct',q[0]);if(state.level<53)state.level++;else $('challengeFeedback').innerHTML+=`<div class="feedback good">🏆 SELAMAT! Kamu menamatkan seluruh 53 level RPG SMK PINTAR!</div>`}else{state.hp-=12;state.score=Math.max(0,state.score-20);$('challengeFeedback').innerHTML=`<div class="feedback bad">❌ Belum tepat.<br>Jawaban: ${escapeHtml(correct)}</div>`;log('answer_wrong',q[0]);if(state.hp<=0){state.hp=50;state.level=Math.max(1,state.level-1);toast('HP habis. Kamu kembali satu level.')}}save();render();$('nextLevel').classList.remove('hidden');$('nextLevel').textContent=state.level<=53?'LANJUT':'TUTUP';$('nextLevel').onclick=()=>{$('challengePanel').classList.add('hidden');render();window.scrollTo({top:0,behavior:'smooth'})}}
async function loadPlayers(){if(APP_SCRIPT_URL.includes('PASTE_')){$('playerRows').innerHTML='<tr><td colspan="9">Isi APP_SCRIPT_URL di script.js terlebih dahulu.</td></tr>';return}try{const r=await fetch(APP_SCRIPT_URL+'?action=players');const d=await r.json();const rows=d.rows||[];const players=rows.filter(r=>r[1]);$('adminStats').innerHTML=`<div>Event: <b>${rows.length}</b></div><div>Pemain unik: <b>${new Set(players.map(r=>r[2]+'|'+r[3])).size}</b></div>`;$('playerRows').innerHTML=rows.slice().reverse().map(r=>`<tr>${r.slice(0,11).map(v=>`<td>${escapeHtml(String(v??''))}</td>`).join('')}</tr>`).join('')}catch(e){$('playerRows').innerHTML='<tr><td colspan="9">Tidak dapat mengambil data. Pastikan URL Web App benar dan aksesnya Anyone.</td></tr>'}}
$('refreshAdmin').onclick=loadPlayers;
render();
